### PR TITLE
Add external trip ref in section

### PR DESCRIPTION
**Pull request by CGantert345**

### CODE REVIEW

**Comment by jspetrak** [comment]
Do we have the same attribute for Trip and TripSpecification? I am fined with that but want to be sure for @nixxus1030

**Comment by CGantert345** [comment]
> Do we have the same attribute for Trip and TripSpecification? I am fined with that but want to be sure for @nixxus1030

Both have an externalRef.

**Review by jspetrak — APPROVED** [review]

**Comment by nixxus1030** [comment]
@jspetrak sorry for the late reply.  I see in the yml they now have a different name (externalRef in trips, externalTripRef. That looks gindeed better to me. Just externalRef in the RequestedSection would have implied it is the requestedSection externalRef. Thank you !

**Comment by jspetrak** [comment]
@nixxus1030 I did `externalTripRef` in the end.

```yaml
externalTripRef:
          description: reference to a trip in case multiple trips are provided
          type: string
          nullable: true
```

**Pull request merged**
