### PR TITLE
adding seat selection fees on version 3.4

### PR DESCRIPTION
**Pull request by CGantert345**

### CODE REVIEW

**Review by jspetrak — APPROVED** [review]

**Comment by jspetrak** [comment]
@CGantert345 The code seams OK. The link to osdm.io did not work yet-do you have an uncommited branch for gh-pages with this change?

**Review by jspetrak — APPROVED** [review]

**Review by Linus-Turnit — COMMENTED** [review]
I like

**Comment by Linus-Turnit** [comment]
After deeper investigation I don't like it any more. 
The selection fee can not be on the layout side since it is trip dependent not coach dependent. Same coach-layout can be used where different selectionFee applies for different departures.
The price shall be in PlacePosition structure.
image

**Comment by CGantert345** [comment]
you are right, this is a mistake. I will move it to place position

**Pull request merged**
