### PR TITLE
Add SelectionFee

### PR DESCRIPTION
**Pull request by Linus-Turnit**
Place selection fee added

### CODE REVIEW

**Comment by Linus-Turnit** [comment]
This is my very first pull request.

**Comment by jspetrak** [comment]
Hello Linus,
The patch itself looks good! Congratulations to your first pull request.
I have linked it to the tracking issue.
@CGantert345 had a requirement to allow selection fee also on compartments when they are selectable. Could you please update the PR?

**Review by jspetrak — CHANGES_REQUESTED** [review]
Missing selection fee on compartment level.

**Comment by schlpbch** [comment]
Unsure we should model it like that.

**Comment by schlpbch** [comment]
Not needed for this version.

**Pull request closed without merging**
