### PR TITLE
Fix14issues

### PR DESCRIPTION
**Pull request by schlpbch**

### CODE REVIEW

**Review by jspetrak — APPROVED** [review]

**Review by CGantert345 — CHANGES_REQUESTED** [review]
the change described to uncomment the route and alternative routes in viaStation actually removes them by comments.

**Comment by schlpbch** [comment]
> the change described to uncomment the route and alternative routes in viaStation actually removes them by comments.

Squills can not produce code due to the recurrsion so we decided to _comment_ the two parts and do the proper fix with you next Friday with you in the call.

See: https://github.com/UnionInternationalCheminsdeFer/OSDM/wiki/meeting-minutes

**Comment by CGantert345** [comment]
> > the change described to uncomment the route and alternative routes in viaStation actually removes them by comments.
> 
> Squills can not produce code due to the recurrsion so we decided to _comment_ the two parts and do the proper fix with you next Friday with you in the call.
> 
> See: https://github.com/UnionInternationalCheminsdeFer/OSDM/wiki/meeting-minutes

**Comment by CGantert345** [comment]
Removing the route and alternative route kills the entire fare functionality. This is not an option. In case Sqills has an issue the can remove it from their private copy, but the elements must stay in the version that goes to ERA.

**Review by CGantert345 — APPROVED** [review]

**Pull request merged**
