### PR TITLE
Update OSDM-online-api-v3.3.0-draft.yml

### PR DESCRIPTION
**Pull request by stinacarlstedt**
Added releaseSpecification structure, and referenced this in the ReleaseOfferRequest element.

### CODE REVIEW

**Comment by ralfbayer-db** [comment]
I would have preferred to simply refer to RefundSpecification, as in 
     releaseSpecifications:
  ...
          items:
            $ref: '#/components/schemas/RefundSpecification'   

to avoid introducing another object with exactly the same content.

**Comment by jspetrak** [comment]
I know we agreed to create a duplicated object on the call, but @ralfbayer-db is right. In the actual API response, the object name is not seen at all. And we can track renaming the object to something more generic for OSDM 4 to keep BC for code generators now.

**Comment by stinacarlstedt** [comment]
I think our reasoning was that we shouldn't assume both endpoints will always have the same requirements. With that being said, given that we now have a structure where the fulfillmentIDs need to be duplicated, I suppose it's fair to assume we will be doing some refactoring anyway, and can make a minimal change now and focus the updates for version 4. @schlpbch , what do you think?

**Comment by stinacarlstedt** [comment]
I've adjusted the patch in accordance with the discussion above.

**Review by schlpbch — APPROVED** [review]
Thx, please back port to < 3.3.0.

**Pull request merged**
