### PR TITLE
Added release candidate for OSDM 2.0.0-RC01

### PR DESCRIPTION
**Pull request by tls-sbb**

### CODE REVIEW

**Comment by jspetrak** [comment]
@tls-sbb The commited YAML file contains unrelated HTML. Please review it.

**Comment by tls-sbb** [comment]
> @tls-sbb The commited YAML file contains unrelated HTML. Please review it.
Thanks for checking it. My fault. Something went wrong on upload. Now its fixed.

**Review by schlpbch — COMMENTED** [review]
Approving request as urgently needed by infosystem and SBB.

**Review by schlpbch — APPROVED** [review]

**Comment by tls-sbb** [comment]
Ciao @jspetrak<https://github.com/jspetrak>
What do you mean with unrelated HTML?


Von: Josef Petrák ***@***.***>
Gesendet: Mittwoch, 28. September 2022 20:58
An: UnionInternationalCheminsdeFer/OSDM ***@***.***>
Cc: Schall Tillmann (IT-PTR-CEN2-SME1 - Extern) ***@***.***>; Mention ***@***.***>
Betreff: Re: [UnionInternationalCheminsdeFer/OSDM] Added release candidate for OSDM 2.0.0-RC01 (PR #308)


@tls-sbb<https://github.com/tls-sbb> The commited YAML file contains unrelated HTML. Please review it.

**Comment by tls-sbb** [comment]
> @tls-sbb Hello, you have already resolved the issue with the commit "Fixed invalid file content".

Yes, issue is fixed since a long time ;-)

**Pull request merged**
