### PR TITLE
making 202 response similar to 200 for post- fulfillment

### PR DESCRIPTION
**Pull request by nixxus1030**

### CODE REVIEW

**Review by jspetrak — CHANGES_REQUESTED** [review]
The same change should be provided to 4.0 being actively developed now.

**Review by jspetrak — CHANGES_REQUESTED** [review]
Do we do the same change to PATCH? `finalizeFulfillments`. After that, `FulfillmentRequestAcceptedResponse` can be removed as not used any more.

**Comment by nixxus1030** [comment]
> Do we do the same change to PATCH? `finalizeFulfillments`. After that, `FulfillmentRequestAcceptedResponse` can be removed as not used any more.

@jspetrak : as far as I can see it is already the case ? the patch fulfillments already return extended fulfillments ?

**Comment by nixxus1030** [comment]
> The same change should be provided to 4.0 being actively developed now.

indeed. applying the change now

**Review by CGantert345 — APPROVED** [review]

**Review by jspetrak — APPROVED** [review]

**Pull request merged**
