### PR TITLE
Update OSDM-Online.yml

### PR DESCRIPTION
**Pull request by CGantert345**
- OneOf removed
- Link not required

### CODE REVIEW

**Review by schlpbch — COMMENTED** [review]
link is required to support the 'embbeding' logic,

 @nixxus1030 is this correct?

**Comment by CGantert345** [comment]
> link is required to support the 'embbeding' logic,
> 
> @nixxus1030 is this correct?

If you embedd objects the link should not be there.

**Comment by nixxus1030** [comment]
Obviously in case a resource is not embedded the self link is an absolute necessity
But I think we should keep the link as mandatory for the following reasons:
1. You should always have at least the self link. While we dont' use the possibility at the moment, it is especially relevant when using projections to select which fields are to be returned. Embedding mechanism is an extreme case of projection where you either include all fields or none. 
2. Links are always relevant, regardless of whether the resource is embedded or not, as they indicate the state of the application by showing the possible actions: even if you embed passengers in the booking, you still need the link to that passenger, and the link to the patch verb allowing to update the passenger.

We can discuss this further on friday if unclear or not aligned

**Comment by CGantert345** [comment]
> Obviously in case a resource is not embedded the self link is an absolute necessity
> But I think we should keep the link as mandatory for the following reasons:
> 
> 1. You should always have at least the self link. While we dont' use the possibility at the moment, it is especially relevant when using projections to select which fields are to be returned. Embedding mechanism is an extreme case of projection where you either include all fields or none.
> 2. Links are always relevant, regardless of whether the resource is embedded or not, as they indicate the state of the application by showing the possible actions: even if you embed passengers in the booking, you still need the link to that passenger, and the link to the patch verb allowing to update the passenger.
> 
> We can discuss this further on friday if unclear or not aligned

**Comment by CGantert345** [comment]
> > Obviously in case a resource is not embedded the self link is an absolute necessity
> > But I think we should keep the link as mandatory for the following reasons:
> > 
> > 1. You should always have at least the self link. While we dont' use the possibility at the moment, it is especially relevant when using projections to select which fields are to be returned. Embedding mechanism is an extreme case of projection where you either include all fields or none.
> > 2. Links are always relevant, regardless of whether the resource is embedded or not, as they indicate the state of the application by showing the possible actions: even if you embed passengers in the booking, you still need the link to that passenger, and the link to the patch verb allowing to update the passenger.
> > 
> > We can discuss this further on friday if unclear or not aligned

Links must be entirely optional, as the delault behaviour is using embedded content, some objects will even never appear as separate resources and a self link adds useless complexity. If we keep it it will be an empty link or filled with garbage.

**Review by schlpbch — APPROVED** [review]

**Pull request merged**
